name: keycloak+SQLServer-Service   

networks:
  local-network:
    external: true
  keycloak_net:
    driver: bridge

volumes:
  sql_vol:
    driver: local
  keycloak_vol:  
    driver: local  

services:
  keycloak_db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    volumes: 
      - sql_vol:/var/opt/mssql
    ports:
      - "1433:1433"
      - "1434:1434"
      - "443:443"
    networks: 
      - local-network   
    environment:      
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}

  keycloak:
    image: jboss/keycloak:8.0.0
    #command: ["-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000", "-Dkeycloak.profile.feature.upload_scripts=enabled"]
    networks: 
      - local-network
    restart: always    
    volumes:
      - keycloak_vol:/opt/jboss/keycloak/realm-config    
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDR}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - keycloak_db

