name: projeto qdrant
services:
  qdrant-service:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant-container
    healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
          interval: 10s
          timeout: 2s
          retries: 5
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant-service_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_data:/qdrant/storage


networks:
  local_network:
    driver: bridge

volumes:
  qdrant_data:
    name: qdrant-service_data


configs:
  qdrant-service_config:
    content: |
      log_level: INFO
