name: Infra-Projetos

networks:
  local_network:
    external: true

volumes:
  postgres-data:
    name: postgres-service_data
  pgadmin-keycloak:
    name: pgadmin-service-keycloak_data 

services:
  pgadmin-service:
    container_name: pgadmin-container
    image: dpage/pgadmin4:8.14.0
    depends_on:
      postgres-service:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: davi.info@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      # 0 - CRITICAL
      # 1 - ERROR
      # 2 - WARNING
      # 3 - INFO
      # 4 - DEBUG
      # 5 - TRACE
      # 10 - NOTSET
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 2
    volumes:
      - pgadmin-keycloak:/var/lib/pgadmin4/storage
    ports:
      - 15437:15432
      - 877:80
    healthcheck:
      test: [ 'CMD', 'wget', '-O', '-', 'http://localhost:80/misc/ping' ]
      interval: 50s
      timeout: 3s
      retries: 10
      start_period: 1m
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    cpuset: '1'

  postgres-service:
    image: postgres:17.2
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgresHost
      POSTGRES_PORT: 5432
      # 0 - EMERGENCY
      # 1 - ALERT
      # 2 - CRITICAL
      # 3 - ERROR
      # 4 - WARNING
      # 5 - NOTICE
      # 6 - INFO
      # 7 - DEBUG
      POSTGRES_LOG_LEVEL: 4
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./01-CriaDatabase_LitellmDB.sql:/docker-entrypoint-initdb.d/01-CriaDatabase_LitellmDB.sql
      - ./02-CriaDatabase_openwebui.sql:/docker-entrypoint-initdb.d/02-CriaDatabase_openwebui.sql
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 50s
      timeout: 5s
      retries: 15
      start_period: 2m
    ports:
        - 5437:5432
    networks:
      - local_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    cpuset: '1'



