name: oracle19c-service

networks:
  local-network:
    external: true

volumes:
  oracle_data:

services:
  oracle:
    image: gvenzl/oracle-free:19.21.0-slim # Or use your specific tag from Docker Hub
    container_name: oracle19c-container
    restart: always
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_SID: orcl # Or your desired SID
      ORACLE_PWD: your_oracle_password # Replace with your desired password
      ORACLE_ALLOW_REMOTE: "true"  # Allow remote connections (optional)
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - local_network
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

