name: postgresspgadmin   
networks:
  local-network:
        external: true
    # Define a named volume for Grafana data
    # This volume will persist Grafana data across container restarts
    # and allow you to keep your dashboards and settings.   
volumes:
  grafana-service:
    name: grafana-service_data
    
services:
  grafana:
    image: grafana/grafana
    restart: always
    container_name: postgres-container
    ports:
      - "3000:3000"
    volumes:
      - grafana-service:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks:
      - local-network 
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    cpuset: '1'

        
  