name: NetWebAPIKC-Service   

networks:
  local-network:
    external: true

volumes:
  postgres_data:
  keycloak_data: 

services:        
  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    hostname: postgres
    restart: unless-stopped
    command: postgres -c shared_buffers=256MB -c work_mem=16MB -c maintenance_work_mem=128MB -c effective_cache_size=512MB -c max_connections=100
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: ${POSTGRES_DB}
       POSTGRES_MULTIPLE_DATABASES: keycloak,langflow
       POSTGRES_PORT: ${POSTGRES_PORT}
       POSTGRES_LOG_LEVEL: ${POSTGRES_LOG_LEVEL}
       PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres-init:/docker-entrypoint-initdb.d      
    ports:
        - 5432:5432
    networks:
      - local-network
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d postgres
      interval: 50s
      timeout: 5s
      retries: 15
      start_period: 2m
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  keycloak-service:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-container
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      #KC_HOSTNAME: localhost
      #KC_HOSTNAME_STRICT: false
      KC_HTTP_PORT: 8080
     # KC_HTTPS_PORT: 7443      
      KC_HOSTNAME_STRICT_FRONTCHANNEL: 'true'
      KC_HTTP_ENABLED: 'true' #PRD false
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HTTP_METRICS_HISTOGRAMS_ENABLED: 'true'
      KC_CACHE_METRICS_HISTOGRAMS_ENABLED: 'true'
      KC_LOG_LEVEL: DEBUG # DEBUG     
      KC_LOG_CONSOLE_COLOR: 'true'  
      KC_PROXY: none
      LANG: pt_BR.UTF-8
   #   KEYCLOAK_IMPORT: /opt/keycloak/data/import/WebAPIKC-realm.json         
   #   KEYCLOAK_EXTRA_ARGS: -Dkeycloak.profile.feature.upload_scripts=enabled -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm/WebAPIKC-realm.json:/opt/keycloak/import/WebAPIKC-realm.json
    #init: true
    command: ['start-dev', '--http-port', '8080'] #,'--import-realm'  '--override', 'true',
   
    ports:
      - 3000:8080
      #- 7443:7443
      #- 9000:9000
    networks:
      - local-network
    depends_on:
      - postgres        
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
      start_period: 2m
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.30'
          memory: 128M    