name: Moodle-Service   

networks:
  local-network:
    external: true


volumes:
  mariadb-data:
    driver: local
  mariadb-logs:
    driver: local
  moodle-data:
    driver: local
  moodledata-data:
    driver: local

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always 
    environment:      
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bitnami_moodle
      MYSQL_USER: bn_moodle
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST:-localhost}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_LOG_LEVEL: ${MYSQL_LOG_LEVEL:-2}
      MYSQL_LOG_ERROR_VERBOSITY: ${MYSQL_LOG_ERROR_VERBOSITY:-2}
      MYSQL_GENERAL_LOG: ${MYSQL_GENERAL_LOG:-1}
      MYSQL_GENERAL_LOG_FILE: ${MYSQL_GENERAL_LOG_FILE:-/var/log/mariadb/general.log}
      MYSQL_CHARSET: ${MYSQL_CHARSET:-utf8mb4}
      MYSQL_COLLATION: ${MYSQL_COLLATION:-utf8mb4_unicode_ci}        
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - mariadb-data:/var/lib/mysql       
      - mariadb-logs:/var/log/mariadb
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      #- ./my.cnf:/etc/mysql/conf.d/my.cnf:ro      
    ports:
     - "3306:3306"
    networks:
     - local-network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --user=$${MYSQL_USER} --password=$${MYSQL_PASSWORD} --host=localhost ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    cpuset: '1'

  moodle:
    image: docker.io/bitnami/moodle:3
    ports:
      - '8085:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
