name: WordPress-Service   

networks:
  local-network:
    external: true

volumes:
  mariadb-data:
    name: mariadb_data
  mariadb-logs:
    name: mariadb_logs
  wordpress-data:
    name: wordpress_data
  wordpress-logs:
    name: wordpress_logs
  wordpress_vol_data:
    name: wordpress_vol_data
  wordpress_vol:
    name: wordpress_vol_data

services:
  dbblog-service:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST:-localhost}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_LOG_LEVEL: ${MYSQL_LOG_LEVEL:-2}
      MYSQL_LOG_ERROR_VERBOSITY: ${MYSQL_LOG_ERROR_VERBOSITY:-2}
      MYSQL_GENERAL_LOG: ${MYSQL_GENERAL_LOG:-1}
      MYSQL_GENERAL_LOG_FILE: ${MYSQL_GENERAL_LOG_FILE:-/var/log/mariadb/general.log}
      MYSQL_CHARSET: ${MYSQL_CHARSET:-utf8mb4}
      MYSQL_COLLATION: ${MYSQL_COLLATION:-utf8mb4_unicode_ci}        
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - mariadb-data:/var/lib/mysql       
      - mariadb-logs:/var/log/mariadb
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      #- ./my.cnf:/etc/mysql/conf.d/my.cnf:ro      
    ports:
     - "3306:3306"
    networks:
     - local-network
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin --user=$${MYSQL_USER} --password=$${MYSQL_PASSWORD} --host=localhost ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    cpuset: '1'

  phpmyadmin-service:
    image: phpmyadmin:latest
    container_name: phpmyadmin-container
    restart: always
    networks:
     - local-network
    ports:
    - 8082:80
    environment:
      - PMA_ARBITRARY=1 
      - PMA_HOST=dbblog-service
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
      - PMA_PORT=${MYSQL_PORT:-3306}
      - PMA_ABSOLUTE_URI=http://localhost:8082      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
    depends_on:
      dbblog-service:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    cpuset: '1'

  wordpress-service:
    image: wordpress:latest
    container_name: wordpress-container
    restart: always
    environment:
      WORDPRESS_DB_HOST: dbblog-service
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
    volumes:
     - wordpress-data:/var/www/html
     - wordpress-logs:/var/log/wordpress
     - wordpress_vol:/var/www/html/wp-content/uploads
    # Uncomment the next line to use a custom configuration file
    # - ./wp-config.php:/var/www/html/wp-config.php:ro
    # Uncomment the next line to use a custom theme
    # - ./wp-content/themes/my-theme:/var/www/html/wp-content/themes/my-theme:ro
    # Uncomment the next line to use a custom plugin
    # - ./wp-content/plugins/my-plugin:/var/www/html/wp-content/plugins/my-plugin:ro
    # Uncomment the next line to use a custom mu-plugin
    # - ./wp-content/mu-plugins/my-mu-plugin:/var/www/html/wp-content/mu-plugins/my-mu-plugin:ro
    # Uncomment the next line to use a custom upload directory
    # - ./wp-content/uploads:/var/www/html/wp-content/uploads:rw
    # Uncomment the next line to use a custom cache directory
    # - ./wp-content/cache:/var/www/html/wp-content/cache:rw
    # Uncomment the next line to use a custom object cache directory
    # - ./wp-content/object-cache:/var/www/html/wp-content/object-cache:rw
    # Uncomment the next line to use a custom database backup directory
    # - ./wp-content/db-backups:/var/www/html/wp-content/db-backups:rw
    # Uncomment the next line to use a custom log directory
    # - ./wp-content/logs:/var/www/html/wp-content/logs:rw    
    ports:
     - "8080:80"
    networks:
     - local-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
    depends_on:
      dbblog-service:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    cpuset: '1'