name: WordPress-Service   

networks:
  local-network:
    external: true

volumes:
  mariadb-data:
    name: mariadb_data
  mariadb-logs:
    name: mariadb_logs
  wordpress-data:
    name: wordpress_data
  wordpress-logs:
    name: wordpress_logs
  wordpress_vol_data:
    name: wordpress_vol_data
  wordpress_vol:
    name: wordpress_vol_data

services:
  dbblog-service:
    image: mariadb:latest
    container_name: dbblog-container
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST:-localhost}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_LOG_LEVEL: ${MYSQL_LOG_LEVEL:-2}
      MYSQL_LOG_ERROR_VERBOSITY: ${MYSQL_LOG_ERROR_VERBOSITY:-2}
      MYSQL_GENERAL_LOG: ${MYSQL_GENERAL_LOG:-1}
      MYSQL_GENERAL_LOG_FILE: ${MYSQL_GENERAL_LOG_FILE:-/var/log/mariadb/general.log}
      MYSQL_CHARSET: ${MYSQL_CHARSET:-utf8mb4}
      MYSQL_COLLATION: ${MYSQL_COLLATION:-utf8mb4_unicode_ci}  
      MYSQL_INITDB_SKIP_TZINFO: "yes"
      MYSQL_INITDB_SKIP_DB_CREATION: "no"
      MYSQL_INITDB_SKIP_LOGGING: "no"
      MYSQL_INITDB_SKIP_PERMISSIONS: "no"
      MYSQL_INITDB_SKIP_AUTHENTICATION: "no"
      MYSQL_INITDB_SKIP_TABLES: "no"
      MYSQL_INITDB_SKIP_DATABASES: "no"
      MYSQL_INITDB_SKIP_USERS: "no"
      MYSQL_INITDB_SKIP_PASSWORDS: "no"
      MYSQL_INITDB_SKIP_ROOT_USER: "no"
      MYSQL_INITDB_SKIP_ROOT_PASSWORD: "no"
      MYSQL_INITDB_SKIP_ROOT_HOST: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANTS: "no"
      MYSQL_INITDB_SKIP_ROOT_PRIVILEGES: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_ALL: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_OPTION: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_REVOKE: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_CREATE: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_DROP: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_ALTER: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_INDEX: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_REFERENCES: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_EXECUTE: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_TRIGGER: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_CREATE_TEMPORARY_TABLES: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_LOCK_TABLES: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_REPLICATION_SLAVE: "no"    
      MYSQL_INITDB_SKIP_ROOT_GRANT_REPLICATION_CLIENT: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_CREATE_VIEW: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_SHOW_VIEW: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_CREATE_ROUTINE: "no"
      MYSQL_INITDB_SKIP_ROOT_GRANT_ALTER_ROUTINE: "no" 
     # MYSQL_INITDB_ARGS: "--init-file /docker-entrypoint-initdb.d/init.sql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    init: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - mariadb-data:/var/lib/mysql       
      - mariadb-logs:/var/log/mariadb
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      #- ./my.cnf:/etc/mysql/conf.d/my.cnf:ro      
    ports:
     - "3306:3306"
    networks:
     - local-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    cpuset: '1'

  blog:
    image: wordpress:latest
    container_name: blog-container
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8080');
        define('WP_SITEURL', 'http://localhost:8080');
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        @ini_set('display_errors', 0);
        define('WP_ALLOW_REPAIR', true);
        define('WP_POST_REVISIONS', 5);
        define('AUTOSAVE_INTERVAL', 120);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '512M');
        define('WP_CACHE', true);
        define('WP_DEFAULT_THEME', 'twentytwentyone');
        define('WP_USE_EXT_MYSQL', false);
        define('WP_AUTO_UPDATE_CORE', true);
        define('DISALLOW_FILE_EDIT', true);
        define('DISALLOW_FILE_MODS', true);
        define('FORCE_SSL_ADMIN', true);
        define('WP_HTTP_BLOCK_EXTERNAL', true);
        define('WP_ACCESSIBLE_HOSTS', 'api.wordpress.org,*.wordpress.org');
        define('WP_REDIS_DISABLED', false);
        define('WP_REDIS_HOST', 'redis'); 
    volumes:
     - wordpress-data:/var/www/html
     - wordpress-logs:/var/log/wordpress
     - wordpress_vol:/var/www/html/wp-content/uploads
    # Uncomment the next line to use a custom configuration file
    # - ./wp-config.php:/var/www/html/wp-config.php:ro
    # Uncomment the next line to use a custom theme
    # - ./wp-content/themes/my-theme:/var/www/html/wp-content/themes/my-theme:ro
    # Uncomment the next line to use a custom plugin
    # - ./wp-content/plugins/my-plugin:/var/www/html/wp-content/plugins/my-plugin:ro
    # Uncomment the next line to use a custom mu-plugin
    # - ./wp-content/mu-plugins/my-mu-plugin:/var/www/html/wp-content/mu-plugins/my-mu-plugin:ro
    # Uncomment the next line to use a custom upload directory
    # - ./wp-content/uploads:/var/www/html/wp-content/uploads:rw
    # Uncomment the next line to use a custom cache directory
    # - ./wp-content/cache:/var/www/html/wp-content/cache:rw
    # Uncomment the next line to use a custom object cache directory
    # - ./wp-content/object-cache:/var/www/html/wp-content/object-cache:rw
    # Uncomment the next line to use a custom database backup directory
    # - ./wp-content/db-backups:/var/www/html/wp-content/db-backups:rw
    # Uncomment the next line to use a custom log directory
    # - ./wp-content/logs:/var/www/html/wp-content/logs:rw    
    ports:
     - "8080:80"
    networks:
     - local-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m
    depends_on:
      dbblog-service:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    cpuset: '1'