# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  netwebapikc:
    image: netwebapikc
    build:
      context: .
      dockerfile: NetWebApiKC/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5111:5111
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
