services:
  redis:
    image: "redis:latest"
    container_name: "redis_container"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    # Uncomment the next line to use a custom configuration file
    # command: ["redis-server", "/usr/local/etc/redis/redis.conf"]  
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      #  - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}

volumes:
  redis_data:

